HealthNetR2/oursite/doctor/urls.py
from django.conf.urls import url

# Url patterns that django follows and directs to the specified views.
urlpatterns = [
    url(r'^$', 'doctor.views.index', name='index'),
    url(r'^editprofile/$', 'doctor.views.edit_profile', name='editprofile'),
    url(r'^appointments/$', 'doctor.views.appointments', name='allappointments'),
    url(r'^makeappointment/$', 'doctor.views.make_appointment', name='makeappointment'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'doctor.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'doctor.views.delete_appointment', name='deleteapp'),
    url(r'^messages/$', 'healthnet.views.user_messages', name='messages'),
    url(r'^allpatients/$', 'doctor.views.all_patients', name='allpatients'),
    url(r'^viewpatient/(?P<pk>[-\w]+)/$', 'doctor.views.view_patient', name='viewpatient'),
    url(r'^makeprescription/(?P<pk>[-\w]+)/$', 'doctor.views.make_prescription', name='makepscript'),
    url(r'^deleteprescription/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.delete_prescription', name='deletepscript'),
    url(r'^maketest/(?P<pk>[-\w]+)/$', 'doctor.views.make_test', name='maketest'),
    url(r'^edittest/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.edit_test', name='edittest'),
    url(r'^deletetest/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.delete_test', name='deletetest'),
    url(r'^transferpatient/(?P<pk>[-\w]+)/$', 'doctor.views.transfer_patient', name='transferpatient'),
    url(r'^uploadfile/(?P<pk>[-\w]+)/$', 'doctor.views.upload_file', name='uploadfile'),
    url(r'^deletefile/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.delete_file', name='deletefile'),
]	

HealthNetR2/oursite/nurse/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'nurse.views.index', name='index'),
    url(r'^search/', 'nurse.views.search_patient', name='patientsearch'),
    url(r'^patientsearch/', 'nurse.views.search_patient', name='patientfound'),
    url(r'^makeappointment/(?P<pk>[-\w]+)/', 'nurse.views.make_appointment', name='makeappointment'),
    url(r'^editprofile/', 'nurse.views.edit_Profile', name='editprofile'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'nurse.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'nurse.views.delete_appointment', name='deleteapp'),
    url(r'^viewpatientappointment/(?P<pk>[-\w]+)/$', 'nurse.views.appointments', name='viewpatientapps'),
    url(r'^allpatients/$', 'nurse.views.all_patients', name='allpatients'),
    url(r'^viewpatient/(?P<pk>[-\w]+)/$', 'nurse.views.view_patient', name='viewpatient'),
]

HealthNetR2/oursite/oursite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'healthnet.views.index', name="home"),
    url(r'^healthnet/', include('healthnet.urls', namespace="healthnet")),
    url(r'^healthnet/admin/', include('administrator.urls', namespace="administrator")),
    url(r'^healthnet/patient/', include('patient.urls', namespace="patient")),
    url(r'^healthnet/nurse/', include('nurse.urls', namespace="nurse")),
    url(r'^healthnet/doctor/', include('doctor.urls', namespace="doctor")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthNetR2/oursite/nurse/models.py
from django.db import models

# Create your models here.

HealthNetR2/oursite/nurse/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from healthnet.models import Appointment, UserProfile, StaffProfile, DoctorProfile, Prescription, Test, PatientFile
from .forms import NurseForm, NurseProfileForm, NurseAppointmentForm
from patient.forms import PatientProfileForm, PatientForm, PatientAppointmentForm
from doctor.forms import DoctorMakeAppoitmentForm
from django.forms.models import model_to_dict
from django import forms
from nurse.templatetags.nurse_tags import *
from django.contrib.auth.decorators import login_required, user_passes_test

import logging;
import json as simplejson
import json
from django.utils.safestring import SafeString

logger = logging.getLogger(__name__)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def index(request):
    """
    Homepage for the nurse
    :param request: Accepts a request object
    :return: The homepage of the Nurse
    """
    appointmentdic = []
    currentUser = StaffProfile.objects.get(user=request.user)
    allUserProfiles = UserProfile.objects.filter(hospital=currentUser.hospital)
    appointments = []
    for e in allUserProfiles:
        appointments += Appointment.objects.filter(user=e.user)
    for appointment in appointments:
        d = appointment.date_time
        starttime = d.strftime("%Y-%m-%dT%H:%M:%S")
        appointmentdic.append({'title': appointment.user.first_name,
                               'start': starttime
                               })

    context = {"allAppointments": SafeString(simplejson.dumps(appointmentdic))}
    return render(request, 'nurse/nurse_index.html', context)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def edit_Profile(request):
    """
    Allows the nurse to edit their profile.
    :param request: Accepts a request object
    :return: Page allowing the nurse to edit profile and save information
    """
    n = StaffProfile.objects.get(user=request.user)
    nurse_form = NurseProfileForm(instance=n)

    if request.method == 'POST':
        nurse_form = NurseProfileForm(data=request.POST,instance=n)
        if nurse_form.is_valid():
            nurse = nurse_form.save(commit=False)
            nurse.hospital = nurse_form.cleaned_data['hospital']
            nurse.save()
            logger.info("Nurse \"" + request.user.username + "\" has edited their profile.")
            return HttpResponseRedirect("/healthnet/nurse/editprofile/")
        else:
            print(nurse_form.errors)

    context = {"nurse_form" : nurse_form}
    return render(request, 'nurse/nurse_edit_profile.html', context)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def search_patient(request):
    """
    Nurses should be able to find a patient and view their prescription
    :param request: Accepts a request object
    :return: A patient prescription
    """
    if request.method == 'POST':
        patientname = request.POST.get('patientname')
        users_in_group = Group.objects.get(name="Patient").user_set.all()

        for patient in users_in_group:
            if patientname == patient.username:
                patientinfo = patient
                context = {"patientinfo": patientinfo}
                logger.info("Patient " + patient.username + " obtained by nurse")
                return render(request, 'nurse/nurse_display_patient.html', context)
        return render(request, 'nurse/nurse_search_patient.html', {"nopatient": "Patient does not exist"})
    else:
        return render(request,'nurse/nurse_search_patient.html', {})

@login_required 
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def all_patients(request):
    """
    Nurse will be able to view all of the patients in their hospital
    :param request: Accepts a request object
    :return: All of the patients in the system
    """
    if request.method == 'GET':
        if 'patientname' in request.GET:
            patient = request.GET.get('patientname')
            user = User.objects.filter(username=patient)
            if user.exists() and user[0].groups.filter(name="Patient"):
                userProfile = UserProfile.objects.filter(user=user)[0]
                pkofuserprofile = userProfile.id
                return view_patient(request,pkofuserprofile)
        if 'home' in request.GET:
            print("HERE")
            return HttpResponseRedirect("/healthnet/nurse/")

        allP = UserProfile.objects.all()
        length = int(allP.count())
    context = {"allp" : allP, "len" : length}
    return render(request, 'nurse/nurse_view_all_patients.html', context)


@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def view_patient(request,pk):
    """
    Nurse will be able to view a specific patient medical information
    :param request: Accepts a request object
    :return: The medical information for a specific user
    """
    userProfile = UserProfile.objects.get(id=pk)
    
    prescriptions = Prescription.objects.filter(user=userProfile.user)
    plen = int(prescriptions.count())

    tests = Test.objects.filter(user=userProfile.user)
    tlen = int(tests.count())

    if request.method == 'GET':
        if 'makepscript' in request.GET:
            return HttpResponseRedirect('/healthnet/nurse/makeprescription/%s/' % userProfile.id)
        elif 'maketest' in request.GET:
            return HttpResponseRedirect('/healthnet/nurse/maketest/%s/' % userProfile.id)
        elif 'update' in request.GET:
            userProfileForm = PatientProfileForm(data=request.GET,instance=userProfile)
            if userProfileForm.is_valid():
                userProfileForm.save()
            userProfile = UserProfile.objects.get(id=pk)
        elif 'allpatients' in request.GET:
            return all_patients(request)
        elif 'admitreleaseform' in request.GET:
            return admit_release_patient(request, userProfile.id)
        elif 'transferpatient' in request.GET:
            return transfer_patient(request, userProfile.id)
        elif 'viewappointments' in request.GET:
            return HttpResponseRedirect("/healthnet/nurse/viewpatientappointment/%s/" % userProfile.pk)
        elif 'home' in request.GET:
            return HttpResponseRedirect("/healthnet/nurse/")

    userForm = PatientForm(data=model_to_dict(userProfile.user))
    userProfileForm = PatientProfileForm(data=model_to_dict(userProfile))

    userProfileForm.fields['hospital'].widget = forms.HiddenInput()

    context = {"userprofile" : userProfile, "userprofileform" : userProfileForm,
    "pscripts" : prescriptions, "tests" : tests, "plen" : plen, "tlen" : tlen,
    "files" : PatientFile.objects.filter(user=userProfile.user),}
    return render(request, 'nurse/nurse_view_patient.html', context)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def admit_release_patient(request, pk):
    """
    Nurse will be able to admit or release a patient
    :param request: Accepts a request object
    :return: Returns the user information with changed admit/release status
    """
    userProfile = UserProfile.objects.get(id=pk)

    if userProfile.is_in_hospital:
        userProfile.is_in_hospital = False
        userProfile.save()
        logger.info("Nurse \"" + request.user.username + "\" has released "
            " Patient \"" + userProfile.user.username + " into " + userProfile.hospital.name + ".")
    else:
        userProfile.is_in_hospital = True
        userProfile.save()
        logger.info("Nurse \"" + request.user.username + "\" has admitted "
            " Patient \"" + userProfile.user.username + "\" out of " + userProfile.hospital.name + ".")

    return HttpResponseRedirect("/healthnet/nurse/viewpatient/%s/" % userProfile.id)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def appointments(request,pk):
    """
    Nurse will be able to view all the appointments for a specific patient
    :param request: Accepts a request object
    :param pk: Private Key of user
    :return: Returns the appointmens for that user
    """
    if request.method == 'POST':
        if 'home' in request.POST:
            return HttpResponseRedirect("/healthnet/nurse/")
        elif 'delete_all' in request.POST:
            user = UserProfile.objects.get(id=pk).user
            allAppointments = Appointment.objects.filter(user=user)
            length = int(allAppointments.count())
            allAppointments = allAppointments.delete()
            length = 0
        elif 'make' in request.POST:
            print("APP: ", UserProfile.objects.get(id=pk).user)
            return HttpResponseRedirect("/healthnet/nurse/makeappointment/%s/" % pk)
    userProfile = UserProfile.objects.get(id=pk)
    allAppointments = Appointment.objects.filter(user=userProfile.user)
    length = int(allAppointments.count())

    context = {"all_appointments" : allAppointments, "len" : length,
    "userprofile" : userProfile,}
    return render(request, 'nurse/nurse_appointment.html', context)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def delete_appointment(request, pk):
    """
    Nurse will be able to delete a specific appointment
    :param request: Accepts a request object
    :param pk: Private key of user
    :return: Return all the appointments without deleted appointment
    """
    ap = Appointment.objects.get(id=pk)
    userid = UserProfile.objects.get(user=ap.user).id
    logger.info("Nurse \"" + request.user.username + "\" has deleted his/her apointment "
                "with Patient \"" + ap.user.username + "\" at " + str(ap.date_time))
    ap.delete()
    return appointments(request, userid)

@login_required
@user_passes_test(is_nurse, login_url='/healthnet/restricted/')
def edit_appointment(request, pk):
    """
    Nurse will be able to admit or release a patient

HealthNetR2/oursite/nurse/templates/nurse/nurse_appointment.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load nurse_tags %}
        <div id="nurse_appt_body">
        {% if user|is_nurse %}
            <h1>Appointments</h1>
            <h2>Nurse: {{ user.first_name }}</h2>
            <form id="alluserappointments" method="post" action="{% url 'nurse:viewpatientapps' userprofile.id %}">{% csrf_token %}
                {% for e in all_appointments %}
                    <p>Patient: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>{{ e.date_time }}
                    <br>Location: {{ e.user|get_location }}
                    {% if len > 0 %}
                        <input type="hidden" name="yes" value=""><br >
                        <a href="{% url 'nurse:editapp' e.id %}"><input type="button" value="Edit"/></a>
                        <a href="{% url 'nurse:deleteapp' e.id %}"><input type="button" value="Delete"/></a>
                    {% endif %}
                    <br>
                {% endfor %}
                <div id="button_box">
                    <input type="submit" name='make' value="Make Appointment" />
                    <input type="submit" name='delete_all' value="Delete All Appointments" onclick="return confirm('Are you sure?')" />
                    <input type="submit" name='home' value="Go Back To Home" />
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_edit_appointment.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Edit Appointment</title>
    </head>
            {% block body_block %}

    {% load nurse_tags %}
    {% if user|is_nurse %}
    <body>
    <div id="nurse_editappt">
        <form method="post" action="{% url 'nurse:editapp' pk %}">
            {% csrf_token %}
            <h1>Edit Appoinment</h1>
            {{ doc_app_form.as_p }}
            {{ appointment_form.as_p }}
            <input type="submit" name="Save" value="Save"/>
            <a href="/healthnet/nurse/appointments/"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}
    {% endblock %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_edit_profile.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit User</title>
</head>
    <body>
        {% block body_block %}
        {% load nurse_tags %}
        {% if user|is_nurse %}
        <div id="nurse_editpro">
        <form id="edit_nurse" method="post" action="/healthnet/nurse/editprofile/">
                {% csrf_token %}
                <h1>Edit Nurse Profile</h1>
                {{ nurse_form.as_p }}
                <button name="save_edit" id="edit_profile" type="submit" >Save</button>
                <a href="/healthnet/nurse/"><input type="button" value="Go Back"/></a>
        </form>
        {% else %}
            {% include "healthnet/index.html" %}
        {% endif %}
        </div>
    {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_index.html
{% extends 'nursebase.html' %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Nurse Homepage</title>

        <link rel='stylesheet' type="text/css" href="{% static 'fullcalendar.css' %}"/>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/fullcalendar.js' %}"></script>
        <script type="text/javascript">
        $(document).ready(function() {
        // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
        // put your options and callbacks here
            })
        });
        </script>
    </head>
    <body>
        {% block body_block %}
        <div id="nurse_index_body">
        {% csrf_token %}
            <h2 id="welcome_title">Welcome To Your HealthNet HomePage</h2>
            <h2>Logged-In As Nurse: {{ user.first_name }}</h2>


        </div>
        {% endblock %}

        {% block cal_block %}
                <div id="calendar"></div>
        {% endblock %}

    </body>
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_make_appointment.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/fullcalendar.js' %}"></script>
        <script type="text/javascript">
        $(document).ready(function() {
        // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
        // put your options and callbacks here
                events: {{ allAppointments }}
            })
        });
        </script>
        <title>Make Appointment</title>
    </head>
    
    {% load nurse_tags %}
    {% if user|is_nurse %}
    <body>
    {% block body_block %}
    <div id="nurse_appt_body">
        <form id="make_appointment" method="post" action="{% url 'nurse:makeappointment' userprofile.id %}">
            {% csrf_token %}
            <h1>Make Appoinment</h1>
            {{ appointment_form.as_p }}
            <input type="submit" name="Submit" value="Submit" />
            <a href="{% url 'nurse:viewpatientapps' userprofile.id %}"><input type="button" value="Cancel"/></a>
        </form>
        </div>
        <div id="calendar"></div>
    </body>
    {% endblock %}
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_search_patient.html
{% extends 'nursebase.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search for a Patient</title>
</head>
<body>
    {% block body_block %}
    <div id="nurse_search_body">
    <h1>Search for a Patients Medical Information</h1>
    <form id="patientsearch" method="post" action="{% url 'nurse:patientfound' %}">
        {% csrf_token %}
        <p>{{ nopatient }}<br/></p>
        Patient name: <input type="text" name="patientname" value="" size="50" />
        <input type ="submit" value="Search" />
        <a href="{% url 'nurse:index' %}"><input type="button" value="Back"/></a>

    </form>
    </div>

    {% endblock %}

        {% block cal_block %}
        {% endblock %}

</body>
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_view_all_appointments.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Appointments</title>
</head>
<body>
  {% block body_block %}
  <div id="nurse_view_all_appt">
  <h1>Scheduled Appointments</h1>
  <form id="allappointments" method="post" action="{% url 'nurse:allappointments'%}">
      {% csrf_token %}
      <br/>
      <br/>
      <br/>
      {% for appointment in appointments %}
      <div id="nurse_list">
      <ul>
            <p>Appointment for {{ appointment.user }}</p>
            <p>Doctor: {{ appointment.doctor }}</p>
            <p>{{ appointment.date_time }}</p>

            {% for usr in userprof %}
                {% if usr.user == appointment.user %}
                    Location: {{ usr.hospital }}
      </ul>
                {% endif %}
            {% endfor %}
            <div id="nurse_edit_button">
            <a href="{% url 'nurse:editapp' appointment.id %}"><input type="button" value="Edit"/></a>
            </div>
      {% endfor %}
      <br/>
          <br/>
          <div id="nurse_buttons">
          <input type="submit" name='make' value="Make Appointment" />
          <a href="{% url 'nurse:index' %}"><input type="button" value="Back"/></a>
          </div>
      </div>
  </form>
  </div>
  {% endblock %}

        {% block cal_block %}
        {% endblock %}
</body>
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_view_all_patients.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load nurse_tags %}
        <div id="nurse_allpatients_body">
        {% if user|is_nurse %}
            <h1>All Patients for Nurse: {{ user.first_name }}</h1>
            <form id="allpatients" method="get" action="{% url 'nurse:allpatients' %}">{% csrf_token %}
                Patient name: <input type="text" name="patientname" value="" size="50" />   
                    <input type ="submit" value="Search" />
                {% for e in allp %}
                    <p>Patient User: {{ e.user.username }}<br>
                    First Name: {{ e.user.first_name }}<br>
                    Last Name {{ e.user.last_name}}
                    {% if len > 0 %}
                        <a href="{% url 'nurse:viewpatient' e.id %}"><input type="button" value="View Patient"/></a>
                        <a href="{% url 'nurse:viewpatientapps' e.id %}"><input type="button" value="View Patient Appointments"/></a>
                    {% endif %}
                    <br>
                {% endfor %}
                <div id="button_box">
                    <input type="submit" name='home' value="Go Back To Home" />
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}
            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/nurse/templates/nurse/nurse_view_patient.html
{% extends 'nursebase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load nurse_tags %}
        {% load doctor_tags %}
        <div id="nurse_viewpatient_body">
        {% if user|is_nurse %}
            <h1>Patient for Nurse: {{ user.first_name }}</h1>
            <form id="viewpatient" method="get" action="{% url 'nurse:viewpatient' userprofile.id %}">{% csrf_token %}
                <b>Username: </b> {{ userprofile.user.username }}<br><br>
                <b>First Name: </b> {{ userprofile.user.first_name }}<br><br>
                <b>Last Name: </b> {{ userprofile.user.last_name }}<br><br>
                <b>Hospital: </b> {{ userprofile.hospital.name }}<br><br>
                <b>Currently Admitted: </b> {{ userprofile.is_in_hospital }}<br>
                {{ userprofileform.as_p }}
                <input type="submit" name='update' value="Update" />
                <br>
                <h2>Prescriptions</h2>
                {% if plen == 0 %}
                    <p> None </p>
                {% endif %}
                {% for e in pscripts %}
                    {% if plen > 0 %}
                    <p>Prescription: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>Name of Prescription: {{ e.name }}
                    <br>Amount to Take: {{ e.amount }}
                    <br>Reason: {{ e.reason }}
                    {% endif %}
                {% endfor %}

                <h2>Tests</h2>
                {% if tlen == 0 %}
                    <p> None </p>
                {% endif %}
                {% for e in tests %}
                    {% if tlen > 0 %}
                    <p>Test: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>Name of Test: {{ e.name_of_test }}
                    <br>Result: {{ e.result }}
                    <br>Reason/Comments: {{ e.reason }}
                    {% endif %}
                {% endfor %}

                <h2>Files</h2>
                {% if files %}
                    {% for e in files %}
                        <b>{{ e.file_name }}{{ e|extension }}
                    {% endfor %}
                {% else %}
                    <p>None</p>
                {% endif %}

                <div id="button_box">
                    <input type="submit" name='allpatients' value="View All Patients" />
                    <input type="submit" name='admitreleaseform' value="Admit/Release Patient" />
                    <input type="submit" name='viewappointments' value="View Patient Appointments" />
                    <input type="submit" name='home' value="Go Back Home" />
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>