HealthNetR2/oursite/healthnet/urls.py
from django.conf.urls import url

# Url patterns that django follows and directs to the specified views.
urlpatterns = [
    url(r'^$', 'healthnet.views.index', name='index'),
    url(r'^logout/$', 'healthnet.views.user_logout', name='logout'),
    url(r'^login/$', 'healthnet.views.user_login', name='login'),
    url(r'^messages/$', 'healthnet.views.user_messages', name='messages'),
    url(r'^newmessage/$', 'healthnet.views.user_new_message', name='newmessage'),
    url(r'^restricted/$', 'healthnet.views.restricted', name='restricted'),
]

HealthNetR2/oursite/nurse/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'nurse.views.index', name='index'),
    url(r'^search/', 'nurse.views.search_patient', name='patientsearch'),
    url(r'^patientsearch/', 'nurse.views.search_patient', name='patientfound'),
    url(r'^makeappointment/(?P<pk>[-\w]+)/', 'nurse.views.make_appointment', name='makeappointment'),
    url(r'^editprofile/', 'nurse.views.edit_Profile', name='editprofile'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'nurse.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'nurse.views.delete_appointment', name='deleteapp'),
    url(r'^viewpatientappointment/(?P<pk>[-\w]+)/$', 'nurse.views.appointments', name='viewpatientapps'),
    url(r'^allpatients/$', 'nurse.views.all_patients', name='allpatients'),
    url(r'^viewpatient/(?P<pk>[-\w]+)/$', 'nurse.views.view_patient', name='viewpatient'),
]

HealthNetR2/oursite/oursite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'healthnet.views.index', name="home"),
    url(r'^healthnet/', include('healthnet.urls', namespace="healthnet")),
    url(r'^healthnet/admin/', include('administrator.urls', namespace="administrator")),
    url(r'^healthnet/patient/', include('patient.urls', namespace="patient")),
    url(r'^healthnet/nurse/', include('nurse.urls', namespace="nurse")),
    url(r'^healthnet/doctor/', include('doctor.urls', namespace="doctor")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthNetR2/oursite/patient/urls.py
from django.conf.urls import url
import healthnet
# Url patterns that django follows and directs to the specified views.
urlpatterns = [
    url(r'^$', 'patient.views.index', name='patient_index'),
    url(r'^register/$', 'patient.views.register', name='register'),
    url(r'^editpatient/$', 'patient.views.edit_patient', name='editpatient'),
    url(r'^appointments/$', 'patient.views.appointments', name='viewappoinments'),
    url(r'^makeappointment/$', 'patient.views.make_appointment', name='makeappointment'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'patient.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'patient.views.delete_appointment', name='deleteapp'),
    url(r'^messages/$', 'healthnet.views.user_messages', name='messages'),
    url(r'^viewmedicalinfo/$', 'patient.views.view_medical_info', name='viewmedicalinfo'),
]

HealthNetR2/oursite/healthnet/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from healthnet.models import UserProfile, DoctorProfile, StaffProfile
from healthnet.models import Message

class MessageForm(forms.ModelForm):
    """
    Message form used for messaging other users
    """
    #checks to see if the username is in existance already
    def clean_to_user(self):
        to = self.cleaned_data['to_user']
        user = self.cleaned_data['from_user']
        if to == user:  
            raise forms.ValidationError('You cannot send a message to yourself.')
            return to
        elif not User.objects.filter(username=to).exists():
            raise forms.ValidationError('"%s" does not exist. Send to valid user.' % to)
            return to
        
        to_user = User.objects.get(username=to)
        from_user = User.objects.get(username=user)
        to_group = to_user.groups.all()[0]
        from_group = from_user.groups.all()[0]

        #patient blocking to only their hospital and to the nurses and doctors
        #of that hospitalx
        if from_group.name == "Patient" and from_group.name == to_group:
            raise forms.ValidationError("You are not allowed to message this user.")
        elif from_group.name == "Patient" and to_group.name == "Doctor" and not DoctorProfile.objects.get(user=to_user).hospital.all().filter(name=UserProfile.objects.get(user=from_user).hospital).exists():
            raise forms.ValidationError("You are not allowed to message this user.")
        elif from_group.name == "Patient" and to_group.name == "Nurse" and UserProfile.objects.get(user=from_user).hospital != StaffProfile.objects.get(user=to_user).hospital:
            raise forms.ValidationError("You are not allowed to message this user.")
        elif from_group.name == "Patient" and to_group.name == "Administrator":
            raise forms.ValidationError("You are not allowed to message this user.")

        #doctor blocking to only their patients of their hospital
        if from_group.name == "Doctor" and to_group.name == "Patient":
            docHospitals = DoctorProfile.objects.get(user=from_user).hospital.all()
            if not docHospitals.filter(name=UserProfile.objects.get(user=to_user).hospital.name).exists():
                raise forms.ValidationError("You are not allowed to message this user.")
        elif from_group.name == "Doctor" and to_group.name == "Administrator":
            raise forms.ValidationError("You are not allowed to message this user.")

        #nurse blocking to only their patients of their hospital
        if from_group.name == "Nurse" and to_group.name == "Patient" and StaffProfile.objects.get(user=from_user).hospital != UserProfile.objects.get(user=to_user).hospital:
            raise forms.ValidationError("You are not allowed to message this user.")
        elif from_group.name == "Nurse" and to_group.name == "Administrator":
            raise forms.ValidationError("You are not allowed to message this user.")

        #admin blocking only other admins of their hospital
        if from_group.name == "Administrator" and to_group.name == "Administrator" and StaffProfile.objects.get(user=from_user).hospital != StaffProfile.objects.get(user=to_user).hospital:
            raise forms.ValidationError("You are not allowed to message this user.")
        elif from_group.name == "Administrator" and to_group.name != "Administrator":
            raise forms.ValidationError("You are not allowed to message this user.")

        return to

    def __init__(self, *args, **kwargs): #change code to understand how this lets in marked up fields
        super(MessageForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True
        self.fields['from_user'].widget.attrs['readonly'] = True

    class Meta:
        model = Message
        fields = ('from_user','to_user','date_time','message')

HealthNetR2/oursite/healthnet/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from healthnet.models import Message, Hospital, StaffProfile
from healthnet.forms import MessageForm
from administrator.forms import StaffProfileForm
from django import forms
from healthnet.templatetags.healthnet_tags import *

def index(request):
    """
    Renders a request object and loads up the index page.
    :param request: Accepts a request object.
    :return: An index.html is rendered showing the homepage and provided links.
    """

    #creates the groups if they do not exist
    if not Group.objects.filter(name="Administrator").exists():
        Group.objects.create(name="Administrator")
    if not Group.objects.filter(name="Doctor").exists():
        Group.objects.create(name="Doctor")
    if not Group.objects.filter(name="Patient").exists():
        Group.objects.create(name="Patient")
    if not Group.objects.filter(name="Nurse").exists():
        Group.objects.create(name="Nurse")
    if Hospital.objects.count() == 0:
        h = Hospital(name="Chesnut Hill Hospital")
        h.save()
        h = Hospital(name="Pennsylvania Central Hospital")
        h.save()

    #adds default admin on the site, when db is cleaned
    if User.objects.filter(groups__name='Administrator').count() == 0:
        user = User.objects.create_user(username="admin",email="admin@rit.edu",password="admin",
            first_name='admin',last_name='admin')

        user.save()

        staff = StaffProfile(user=user,hospital=Hospital.objects.get(name="Chesnut Hill Hospital"),
            previous_employment="Somewhere",education_information="None what so ever", accreditation="Nothing")
        staff.save()
        
        #adds the admin to the group
        user.groups.add(Group.objects.filter(name="Administrator")[0])
        user.save()

    if request.user.is_authenticated():
        user = request.user
        user_group = user.groups.all()[0].name
        if user_group == "Administrator":
            user_group = "admin"
        return HttpResponseRedirect("/healthnet/" + user_group.lower() + "/")
    return render(request, "healthnet/index.html")

def user_logout(request):
    """
    The user is logged out of his account an returned to the homepage.
    :param request: Accepts a request object.
    :return: A user is logged out, and returned to the homepage.
    """
    # Since user is logged in, we can just log them out.
    if request.user.is_authenticated():
        logout(request)
    # Takes the user back to the index page.
    return HttpResponseRedirect("/healthnet/")

def user_login(request):
    """
    Allows a user to attempt to login with the right credentials
    :param request: Accepts a request object.
    :return: A user is logged out, and returned to the homepage.
    """
    #redirects user back to homepage
    if request.user.is_active:
        return HttpResponseRedirect("/healthnet/")

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                user = request.user
                user_group = user.groups.all()[0].name
                if user_group == "Administrator":
                    user_group = "admin"
                return HttpResponseRedirect("/healthnet/" + user_group.lower() + "/")
            else:
                return render(request, 'healthnet/index.html', {"login" : "Incorrect Login Username or password"})
        else:
            return render(request, 'healthnet/index.html', {"login" : "Incorrect Login Username or password"})
    else:
        return render(request, 'healthnet/index.html', {})

@login_required
def user_messages(request):
    if request.method == 'POST' and request.user.is_authenticated():
        user = request.user
        #establish which group the user is in
        user_group = user.groups.all()[0].name
        if user_group == "Administrator":
            user_group = "admin"
        return HttpResponseRedirect("/healthnet/" + user_group.lower() + "/")

    from_messages = Message.objects.filter(from_user=request.user.username)
    to_messages = Message.objects.filter(to_user=request.user.username)
    all_messages = from_messages | to_messages

    user = User.objects.get(pk=request.user.id)
    group = user.groups.all()[0].name.lower()
    if group == "administrator":
        group = "admin"
    group += "base.html"

    context = {"all_messages" : all_messages, "group" : group}
    return render(request, 'healthnet/message.html', context)

@login_required
def user_new_message(request):
    message_form = MessageForm()
    message_form.fields['from_user'].initial = request.user.username

    if "submit" in request.POST:
        message_form = MessageForm(data=request.POST)
        if message_form.is_valid():
            message_form.save()
            return HttpResponseRedirect("/healthnet/messages/")
    elif "cancel" in request.POST:
        return HttpResponseRedirect("/healthnet/messages/")

    message_form.fields['date_time'].widget = forms.HiddenInput()

    user = User.objects.get(pk=request.user.id)
    group = user.groups.all()[0].name.lower()
    if group == "administrator":
        group = "admin"
    group += "base.html"

    context = {"message_form": message_form, "group" : group}
    return render(request, 'healthnet/new_message.html', context)

def restricted(request):
    if request.user.is_authenticated:
        context = {"message" : "Access Restricted"}
    else:
        context = {"message" : "Login Required"}
    return render(request, 'healthnet/restricted.html', context)

HealthNetR2/oursite/healthnet/templates/healthnet/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
        <title>HealthNet Homepage</title>
    </head>

    <body id="index_bod">
    <div id="layer">
    <!--<h1><span style="color: red; font-family: Arial";>H</span><span style="color: red; font-family: Arial";">N</span></h1>-->
    </div>
    <div id="master_index">
        <h1>Welcome to HealthNet</h1>
            {% csrf_token %}
            <form id="user_login" method="post" action="{% url 'healthnet:login' %}">
            {% csrf_token %}
            <p>{{ login }}<br /></p>
            {% if active_user %}
                <li><a href="/healthnet/logout/">Logout</a></li><br />
            {% endif %}
            <div id="login_box">
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />
                </div>
                <div id="index_button">
                <input type="submit" value="submit" />
                </div>
            <div id="reg_link">
            <li><a href="{% url 'patient:register' %}">New Patients Click Here To Register</a></li><br />
            </div>
        </form>
        </div>
    </body>
</html>

HealthNetR2/oursite/healthnet/templates/healthnet/makeappointment.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
    <title>HealthNet Make Appointment</title>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Make an appointment</h1>

    <form id="appointmentForm" method="post" action="/healthnet/appointment/">{% csrf_token %}

        {{ appointment.as_p }}

        <input type="submit" value="Submit Appointment" />
        <a href="{% url 'healthnet:index' %}"><input type="button" value="Go Back to Home"/></a>

    </form>

</body>
</html>

HealthNetR2/oursite/healthnet/templates/healthnet/message.html
{% extends group %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Messages</title>
    </head>

    <body>
    {% block body_block %}
      <div id="message_body">
        <form id="make_appointment" method="post" action="{% url 'healthnet:messages' %}">
            {% csrf_token %}
            <h1>Messages</h1>
            {% for e in all_messages %}
                From: {{ e.from_user }}
                To: {{ e.to_user }}
                <br>
                Date/Time: {{ e.date_time }}
                <br>
                Message: {{ e.message }}
                <br>
                <br>
			{% endfor %}
            <input type="submit" name="Go Back" value="Go Back" />
            <br>
            <a href="/healthnet/newmessage/"><input type="button" value="New Message"/></a>
        </form>
      </div>

    {% endblock %}

      {% block cal_block %}
        {% endblock %}
    </body>

</html>

HealthNetR2/oursite/healthnet/templates/healthnet/new_message.html
{% extends group %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>New Message</title>
    </head>

    <body>
        {% block body_block %}

      <div id="new_message_body">
        <h1>New Message</h1>
        <form id="make_appointment" method="post" action="{% url 'healthnet:newmessage' %}">
            {% csrf_token %} 
            {{ message_form.as_p }}
            <input type="submit" name="submit" value="Submit"/>
            <input type="submit" name="cancel" value="Cancel and Go Back"/>
        </form>
      </div>
        {% endblock %}
      {% block cal_block %}
      {% endblock %}
    </body>
</html>

HealthNetR2/oursite/healthnet/templates/healthnet/restricted.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>New Message</title>
    </head>

    <body>
        <div id="restricted_body">
            <div id="box">
            <h1>{{message}}</h1>
            <form id="restricted_page" method="post" action="{% url 'healthnet:index' %}">
            {% csrf_token %}
            <div><span id="time"></span></div>
            </form>
            </div>
        </div>
    </body>
</html>

<script>
    function startTimer(duration, display) 
    {
        var timer = duration, minutes, seconds;
        setInterval(function () {
            seconds = parseInt(timer % 60, 10);

            display.textContent = "Redirecting in: " + seconds;

            if(--timer < 0)
            {
                document.forms['restricted_page'].submit();
            }
        }, 1000);
    }

window.onload = function () {
    var time = 2,
        display = document.querySelector('#time');
    startTimer(time, display);
};
</script>