HealthNetR2/oursite/nurse/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'nurse.views.index', name='index'),
    url(r'^search/', 'nurse.views.search_patient', name='patientsearch'),
    url(r'^patientsearch/', 'nurse.views.search_patient', name='patientfound'),
    url(r'^makeappointment/(?P<pk>[-\w]+)/', 'nurse.views.make_appointment', name='makeappointment'),
    url(r'^editprofile/', 'nurse.views.edit_Profile', name='editprofile'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'nurse.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'nurse.views.delete_appointment', name='deleteapp'),
    url(r'^viewpatientappointment/(?P<pk>[-\w]+)/$', 'nurse.views.appointments', name='viewpatientapps'),
    url(r'^allpatients/$', 'nurse.views.all_patients', name='allpatients'),
    url(r'^viewpatient/(?P<pk>[-\w]+)/$', 'nurse.views.view_patient', name='viewpatient'),
]

HealthNetR2/oursite/oursite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'healthnet.views.index', name="home"),
    url(r'^healthnet/', include('healthnet.urls', namespace="healthnet")),
    url(r'^healthnet/admin/', include('administrator.urls', namespace="administrator")),
    url(r'^healthnet/patient/', include('patient.urls', namespace="patient")),
    url(r'^healthnet/nurse/', include('nurse.urls', namespace="nurse")),
    url(r'^healthnet/doctor/', include('doctor.urls', namespace="doctor")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthNetR2/oursite/patient/urls.py
from django.conf.urls import url
import healthnet
# Url patterns that django follows and directs to the specified views.
urlpatterns = [
    url(r'^$', 'patient.views.index', name='patient_index'),
    url(r'^register/$', 'patient.views.register', name='register'),
    url(r'^editpatient/$', 'patient.views.edit_patient', name='editpatient'),
    url(r'^appointments/$', 'patient.views.appointments', name='viewappoinments'),
    url(r'^makeappointment/$', 'patient.views.make_appointment', name='makeappointment'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'patient.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'patient.views.delete_appointment', name='deleteapp'),
    url(r'^messages/$', 'healthnet.views.user_messages', name='messages'),
    url(r'^viewmedicalinfo/$', 'patient.views.view_medical_info', name='viewmedicalinfo'),
]

HealthNetR2/oursite/patient/models.py
from django.db import models

# Create your models here.

HealthNetR2/oursite/patient/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User, Group
from patient.templatetags.patient_tags import *
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import *
from healthnet.models import UserProfile, Appointment, Prescription, Test, PatientFile
from django import forms
from django.core import serializers
from django.forms.models import model_to_dict
import logging;
import json as simplejson
import json
from django.utils.safestring import SafeString

logger = logging.getLogger(__name__)

@login_required
@user_passes_test(is_patient, login_url='/healthnet/restricted/')
def index(request):
    """
    Homepage for the patient
    :param request: Accepts a request object
    :return: The homepage of the Nurse
    """
    appointmentdic = []
    currentUser = UserProfile.objects.get(user=request.user)
    allUserProfiles = UserProfile.objects.filter(hospital=currentUser.hospital)
    appointments = []
    for e in allUserProfiles:
        appointments += Appointment.objects.filter(user=e.user)
    for appointment in appointments: 
        d = appointment.date_time
        starttime = d.strftime("%Y-%m-%dT%H:%M:%S")
        if request.user.username == appointment.user.username:
            appointmentdic.append({'title': appointment.user.first_name,
                                   'start': starttime
                                   })
        else:
            appointmentdic.append({'title':"Dr " + appointment.doctor.user.first_name,
                                    'start':starttime
                                   })
    context = {"allAppointments": SafeString(simplejson.dumps(appointmentdic))}
    return render(request, 'patient/patient_index.html', context)

def register(request):
    """
    Allows new patients to register
    :param request: Accepts a request object
    :return: Page allowing the patients to register in the system
    """
    if request.method == 'POST':
        patient_form = PatientForm(data=request.POST)
        patient_profile_form = PatientProfileForm(data=request.POST)

        if patient_form.is_valid() and patient_profile_form.is_valid():
            user = patient_form.save()
            user.set_password(user.password)
            #adds user to group
            #pulls the cleaned data of the group choice
            group = Group.objects.get(name="Patient")
            user.groups.add(group)
            user.save()

            profile = patient_profile_form.save(commit=False)
            profile.user = user
            profile.save()
            logger.info("User \"" + user.username + "\" has been registered")
            return HttpResponseRedirect("/healthnet/")
        else:
            print(patient_form.errors, patient_profile_form.errors)

    else:
        patient_form = PatientForm()
        patient_profile_form = PatientProfileForm()

    context = {"patient_form" : patient_form, "patient_profile_form" : patient_profile_form}
    return render(request, 'patient/patient_register.html', context)

@login_required
@user_passes_test(is_patient, login_url='/healthnet/restricted/')
def edit_patient(request):
    """
    Patient can edit their profile. Also allows the patient
    to export their data.
    :param request: Accepts a request object
    :return: Page allowing the patient to edit profile and save information
    """
    if request.method == 'POST':
        #used to export the data if clicked on
        if 'export' in request.POST:
            import csv
            from django.utils.encoding import smart_str
            userProfile = UserProfile.objects.get(user=request.user)
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = str("attachment; filename=" + 
                userProfile.user.first_name + "_" +
                userProfile.user.last_name + "_Profile_Information.csv")
            writer = csv.writer(response, csv.excel)
            response.write(u'\ufeff'.encode('utf8'))
            writer.writerow([
                smart_str(u"Username"),
                smart_str(userProfile.user.username)
            ])
            writer.writerow([
                smart_str(u"First Name"),
                smart_str(userProfile.user.first_name)
            ])
            writer.writerow([
                smart_str(u"Last Name"),
                smart_str(userProfile.user.last_name)
            ])
            writer.writerow([
                smart_str(u"Age"),
                smart_str(userProfile.age)
            ])
            writer.writerow([
                smart_str(u"Date of Birth"),
                smart_str(userProfile.date_of_birth)
            ])
            writer.writerow([
                smart_str(u"Spouse First Name"),
                smart_str(userProfile.spouse_first_name)
            ])
            writer.writerow([
                smart_str(u"Next of Kin"),
                smart_str(userProfile.next_of_kin)
            ])
            writer.writerow([
                smart_str(u"Emergency Contact"),
                smart_str(userProfile.emergency_contact)
            ])
            writer.writerow([
                smart_str(u"Phone Number"),
                smart_str(userProfile.phone_number)
            ])
            writer.writerow([
                smart_str(u"Sex"),
                smart_str(userProfile.sex)
            ])
            writer.writerow([
                smart_str(u"Weight"),
                smart_str(userProfile.weight)
            ])
            writer.writerow([
                smart_str(u"Height"),
                smart_str(userProfile.height)
            ])
            writer.writerow([
                smart_str(u"Insurance"),
                smart_str(userProfile.insurance)
            ])
            writer.writerow([
                smart_str(u"Hospital"),
                smart_str(userProfile.hospital.name)
            ])
            return response
        else:
            #else it assumes that the patient is updating their data
            patient_form = PatientForm(data=request.POST,instance=request.user)
            patient_form.fields['password'].required = False
            patient_profile_form = PatientEditProfileForm(instance=UserProfile.objects.filter(user=request.user)[0],data=request.POST)
            if patient_form.is_valid() and patient_profile_form.is_valid():
                user = patient_form.save()
                user.save()

                profile = patient_profile_form.save(commit=False)
                profile.user = user
                profile.save()

                logger.info("Patient \"" + user.username + "\" has edited his/her info")
                return HttpResponseRedirect("/healthnet/patient/")
            else:
                print(patient_form.errors, patient_profile_form.errors)
    else:
        patient_form = PatientForm(instance=request.user)
        patient_profile_form = PatientEditProfileForm(instance=UserProfile.objects.filter(user=request.user)[0])

    patient_form.fields['username'].widget = forms.HiddenInput()
    patient_form.fields['password'].required = False

    context = {"patient_form" : patient_form, "patient_profile_form" : patient_profile_form}
    return render(request, 'patient/patient_edit_patient.html', context)

@login_required
@user_passes_test(is_patient, login_url='/healthnet/restricted/')
def make_appointment(request):
    """
    Patient should be able to create or update an appointment with a doctor and at one of the doctor's
    available location
    :param request: Accepts a request object
    :return: An appointment
    """
    if request.method == 'POST':
        #sets up the doctor for the appointment
        appointment_form = PatientAppointmentForm(data=request.POST)

        if appointment_form.is_valid():
            appointment = appointment_form.save(commit=False)
            appointment.user = request.user
            appointment.save()
            logger.info("Patient \"" + appointment.user.username + "\" has added an apointment "
                "with Doctor " + appointment.doctor.user.username + " at " + str(appointment.date_time))
            return HttpResponseRedirect("/healthnet/patient/appointments/")
        else:
            print(appointment_form.errors)
    else:
        appointment_form = PatientAppointmentForm()
    h = UserProfile.objects.get(user=request.user).hospital
    dp = DoctorProfile.objects.filter(hospital=h)
    appointment_form.fields['doctor'].queryset = dp

    context = {"appointment_form" : appointment_form}
    return render(request, 'patient/patient_make_appointment.html', context)

@login_required
@user_passes_test(is_patient, login_url='/healthnet/restricted/')
def appointments(request):
    """
    Patient views all of the avaiable appointments
    :param request: Accepts a request object
    :return: All appointments for that user
    """
    appointments = Appointment.objects.all()
    appointments = appointments.filter(user=request.user)
    if request.method == 'POST':
        if 'home' in request.POST:
            return HttpResponseRedirect("/healthnet/patient/")
        elif 'delete_all' in request.POST:
            appointments = appointments.delete()
        elif 'make' in request.POST:
            return HttpResponseRedirect("/healthnet/patient/makeappointment/")

    allAppointments = Appointment.objects.filter(user=request.user)
    context = {"all_appointments" : allAppointments, "len" : allAppointments.count(),
    "location" : UserProfile.objects.get(user=request.user).hospital,}
    return render(request, 'patient/patient_appointment.html', context)

@login_required
@user_passes_test(is_patient, login_url='/healthnet/restricted/')
def edit_appointment(request, pk):
    """
    Patient will be able to edit their appointments

HealthNetR2/oursite/patient/templates/patient/patient_appointment.html
{% extends 'patientbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Patient Homepage</title>
    </head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        <div id="patient_appt_body">
        {% load patient_tags %}
        {% if user|is_patient %}
            <h1>Appointments</h1>
            <h2>Patient: {{ user.first_name }}</h2>
            <form id="alluserappointments" method="post" action="/healthnet/patient/appointments/">{% csrf_token %}
                {% for e in all_appointments %}
                    <p>Doctor: {{ e.doctor }}
                    <br>{{ e.date_time }}
                    <br>Location: {{ location }}
                    {% if len > 0 %}
                        <input type="hidden" name="yes" value=""><br >
                        <a href="{% url 'patient:editapp' e.id %}"><input type="button" value="Edit"/></a>
                        <a href="{% url 'patient:deleteapp' e.id %}"><input type="button" value="Delete"/></a>
                    {% endif %}
                    <br>
                {% endfor %}
                <div id="button_box">
                    <input type="submit" name='make' value="Make Appointment" />
                    <input type="submit" name='delete_all' value="Delete All Appointments" onclick="return confirm('Are you sure?')" />
                    <input type="submit" name='home' value="Go Back To Home" />
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/patient/templates/patient/patient_edit_appointment.html
{% extends 'patientbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Edit Appointment</title>
    </head>
            {% block body_block %}

    {% load patient_tags %}
    {% if user|is_patient %}
    <body>
    <div id="patient_editappt">
        <form method="post" action="{% url 'patient:editapp' pk %}">
            {% csrf_token %}
            <h1>Edit Appoinment</h1>
            {{ appointment_form.as_p }}
            <input type="submit" name="Save" value="Save"/>
            <a href="/healthnet/patient/appointments/"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}
    {% endblock %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/patient/templates/patient/patient_edit_patient.html
{% extends 'patientbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Edit User</title>
    </head>

    <body>
            {% block body_block %}

        {% load patient_tags %}
        {% if user|is_patient %}
        <div id="patient_editpro">
        <form id="edit_patient" method="post" action="/healthnet/patient/editpatient/">
                {% csrf_token %}
                <h1>Edit User</h1>
                {{ patient_form.as_p }}
                {{ patient_profile_form.as_p }}
                <button name="edit_patient" id="edit_patient" type="submit" >Save</button>
                <input type="submit" name="export" value="Export User Medical Information" onclick="return confirm('PRIVACY WARNING EXPORTING ABOUT TO EXPORT MEDICAL DATA')"/>
                <a href="/healthnet/patient/"><input type="button" value="Cancel and Back"/></a>
        </form>
        {% else %}
            {% include "healthnet/index.html" %}
        {% endif %}
        </div>
    {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/patient/templates/patient/patient_index.html
{% extends 'patientbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>

    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Patient Homepage</title>
    </head>

    <body>
            {% block body_block %}
            <div id="patient_index_body">

            {% csrf_token %}
            {% load patient_tags %}
            {% if user|is_patient %}
            <h2 id="welcome_title">Welcome To Your HealthNet HomePage</h2>
            <h2>Logged-In As Patient: {{ user.first_name }}</h2>

            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>

        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/patient/templates/patient/patient_make_appointment.html
{% extends 'patientbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/fullcalendar.js' %}"></script>
        <script type="text/javascript">
        $(document).ready(function() {
        // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
        // put your options and callbacks here
                events: {{ allAppointments }}
            })
        });
        </script>
        <title>Make Appointment</title>
    </head>
    
    {% load patient_tags %}
    {% if user|is_patient %}
    <body>
    {% block body_block %}
    <div id="patient_appt_body">
        <form id="make_appointment" method="post" action="/healthnet/patient/makeappointment/">
            {% csrf_token %}
            <h1>Make Appoinment</h1>
            {{ appointment_form.as_p }}
            <input type="submit" name="Submit" value="Submit" />
            <a href="/healthnet/patient/appointments/"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% endblock %}
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}
        {% block cal_block %}
        {% endblock %}


</html>

HealthNetR2/oursite/patient/templates/patient/patient_register.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>New Patient</title>
    </head>

    <body>
    <div id="patient_reg">
        <form id="create_user" method="post" action="/healthnet/patient/register/">
            {% csrf_token %}
            <h1>New Patient</h1>
            {{ patient_form.as_p }}
            {{ patient_profile_form.as_p }}
            <input type="submit" name="submit" value="Register" />
            <a href="/healthnet/"><input type="button" value="Cancel"/></a>
        </form>
        </div>

            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/patient/templates/patient/patient_view_medical_info.html
{% extends 'patientbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load patient_tags %}
        {% load doctor_tags %}
        <div id="patient_medical_body">
        {% if user|is_patient %}
            <h1>All Medical Information for Patient: {{ user.first_name }}</h1>
            <form id="viewpatient" method="post" action="{% url 'patient:viewmedicalinfo' %}">{% csrf_token %}
                <h2>Prescriptions</h2>
                {% if plen == 0 %}
                    <p> None </p>
                {% endif %}
                {% for e in pscripts %}
                    {% if plen > 0 %}
                    <p>Prescription: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>Name of Prescription: {{ e.name }}
                    <br>Amount to Take: {{ e.amount }}
                    <br>Reason: {{ e.reason }}
                    {% endif %}
                {% endfor %}

                <h2>Tests</h2>
                {% if tlen == 0 %}
                    <p> None </p>
                {% endif %}
                {% for e in tests %}
                    {% if tlen > 0 %}
                    <p>Test: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>Name of Test: {{ e.name_of_test }}
                    <br>Result: {{ e.result }}
                    <br>Reason/Comments: {{ e.reason }}
                    {% endif %}
                {% endfor %}

                <h2>Files (Click FileName to View/Download)</h2>
                {% if files %}
                    {% for e in files %}
                        <a href="{{ e.patient_file.url }}">{{ e.file_name }}{{ e|extension }}</a><br>
                    {% endfor %}
                {% else %}
                    <p>None</p>
                {% endif %}
                <br>
                <br>
                <input type="submit" name="export" value="Export Medical Information (Test and Prescriptions)" onclick="return confirm('PRIVACY WARNING EXPORTING ABOUT TO EXPORT MEDICAL DATA')"/>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}
            {% block cal_block %}
        {% endblock %}
    </body>
</html>