HealthNetR2/oursite/doctor/urls.py
from django.conf.urls import url

# Url patterns that django follows and directs to the specified views.
urlpatterns = [
    url(r'^$', 'doctor.views.index', name='index'),
    url(r'^editprofile/$', 'doctor.views.edit_profile', name='editprofile'),
    url(r'^appointments/$', 'doctor.views.appointments', name='allappointments'),
    url(r'^makeappointment/$', 'doctor.views.make_appointment', name='makeappointment'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'doctor.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'doctor.views.delete_appointment', name='deleteapp'),
    url(r'^messages/$', 'healthnet.views.user_messages', name='messages'),
    url(r'^allpatients/$', 'doctor.views.all_patients', name='allpatients'),
    url(r'^viewpatient/(?P<pk>[-\w]+)/$', 'doctor.views.view_patient', name='viewpatient'),
    url(r'^makeprescription/(?P<pk>[-\w]+)/$', 'doctor.views.make_prescription', name='makepscript'),
    url(r'^deleteprescription/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.delete_prescription', name='deletepscript'),
    url(r'^maketest/(?P<pk>[-\w]+)/$', 'doctor.views.make_test', name='maketest'),
    url(r'^edittest/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.edit_test', name='edittest'),
    url(r'^deletetest/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.delete_test', name='deletetest'),
    url(r'^transferpatient/(?P<pk>[-\w]+)/$', 'doctor.views.transfer_patient', name='transferpatient'),
    url(r'^uploadfile/(?P<pk>[-\w]+)/$', 'doctor.views.upload_file', name='uploadfile'),
    url(r'^deletefile/(?P<pk>[-\w]+)/(?P<pk2>[-\w]+)/$', 'doctor.views.delete_file', name='deletefile'),
]	

HealthNetR2/oursite/nurse/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'nurse.views.index', name='index'),
    url(r'^search/', 'nurse.views.search_patient', name='patientsearch'),
    url(r'^patientsearch/', 'nurse.views.search_patient', name='patientfound'),
    url(r'^makeappointment/(?P<pk>[-\w]+)/', 'nurse.views.make_appointment', name='makeappointment'),
    url(r'^editprofile/', 'nurse.views.edit_Profile', name='editprofile'),
    url(r'^editappointment/(?P<pk>[-\w]+)/$', 'nurse.views.edit_appointment', name='editapp'),
    url(r'^deleteappointment/(?P<pk>[-\w]+)/$', 'nurse.views.delete_appointment', name='deleteapp'),
    url(r'^viewpatientappointment/(?P<pk>[-\w]+)/$', 'nurse.views.appointments', name='viewpatientapps'),
    url(r'^allpatients/$', 'nurse.views.all_patients', name='allpatients'),
    url(r'^viewpatient/(?P<pk>[-\w]+)/$', 'nurse.views.view_patient', name='viewpatient'),
]

HealthNetR2/oursite/oursite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'healthnet.views.index', name="home"),
    url(r'^healthnet/', include('healthnet.urls', namespace="healthnet")),
    url(r'^healthnet/admin/', include('administrator.urls', namespace="administrator")),
    url(r'^healthnet/patient/', include('patient.urls', namespace="patient")),
    url(r'^healthnet/nurse/', include('nurse.urls', namespace="nurse")),
    url(r'^healthnet/doctor/', include('doctor.urls', namespace="doctor")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthNetR2/oursite/doctor/models.py
from django.db import models

# Create your models here.

HealthNetR2/oursite/doctor/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from healthnet.models import UserProfile, Appointment, Prescription, Test, Transfer, PatientFile
import datetime
from django.forms import extras
from django.contrib.admin.widgets import AdminDateWidget
from django.utils import timezone

class DoctorMakeAppoitmentForm(forms.Form):
    """
    Doctor form used for the updating the appointment information
    """
    username = forms.CharField(max_length=200)
    #checks to see if the username is in existance already
    def clean_username(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('"%s" is not a patient.' % username)
        return username

    def __init__(self, *args, **kwargs):
        super(DoctorMakeAppoitmentForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

class DoctorUserForm(forms.ModelForm):
    """
    Doctor form used for the updating the doctors user information
    """
    password = forms.CharField(widget=forms.PasswordInput(render_value = True))

    #checks to see if the username is in existance already
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.exclude(pk=self.instance.pk).filter(username=username).exists():
            raise forms.ValidationError('"%s" is already in use.' % username)
        return username

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = User
        fields = ('username', 'email', 'password','first_name','last_name')

class PrescriptionForm(forms.ModelForm):
    """
    Doctor form used for the updating the Prescription information
    """
    def __init__(self, *args, **kwargs): #change code to understand how this lets in marked up fields
        super(PrescriptionForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = Prescription
        fields = ('name', 'amount','reason',)

class TestForm(forms.ModelForm):
    """
    Doctor form used for the updating the test information
    """
    def __init__(self, *args, **kwargs): #change code to understand how this lets in marked up fields
        super(TestForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = Test
        fields = ('name_of_test', 'result','reason',)

class AdmitReleaseForm(forms.ModelForm):
    """
    Doctor form used for the updating the admit/release information
    """
    def __init__(self, *args, **kwargs):
        super(AdmitReleaseForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = UserProfile
        fields = ('is_in_hospital',)

class TransferForm(forms.ModelForm):
    """
    Doctor form used for the updating the transfer information
    """
    def __init__(self, *args, **kwargs):
        super(TransferForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = Transfer
        fields = ('reason', 'to_hospital',)

class UploadFileForm(forms.ModelForm):
    """
    Doctor form used for the updating the file information
    """
    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        
        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = PatientFile
        fields = ('patient_file','file_name',)

HealthNetR2/oursite/doctor/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from doctor.templatetags.doctor_tags import *
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from healthnet.models import DoctorProfile, Appointment, Prescription, Test, Hospital
from doctor.forms import *
from patient.forms import PatientAppointmentForm, PatientProfileForm, PatientForm
from doctor.templatetags.doctor_tags import *
from django.forms.models import model_to_dict
from administrator.forms import DoctorProfileForm
from django import forms

import logging;
import json as simplejson
import json
from django.utils.safestring import SafeString

logger = logging.getLogger(__name__)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def index(request):
    """
    Doctor index page is loaded
    :param request: Accepts a request object.
    :return: The index page for the doctor
    """
    appointmentdic = []
    appointments = Appointment.objects.filter(doctor=DoctorProfile.objects.get(user=request.user))
    for appointment in appointments:
        d = appointment.date_time
        starttime = d.strftime("%Y-%m-%dT%H:%M:%S")
        appointmentdic.append({'title': appointment.user.first_name,
                               'start': starttime
                               })
    context = {"allAppointments": SafeString(simplejson.dumps(appointmentdic))}
    return render(request, 'doctor/doctor_index.html', context)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def all_patients(request):
    """
    Doctor view for all of the patients in the system
    :param request: Accepts a request object.
    :return: The list of patients in html page
    """
    if request.method == 'GET':
        if 'patientname' in request.GET:
            patient = request.GET.get('patientname')
            user = User.objects.filter(username=patient)
            if user.exists() and user[0].groups.filter(name="Patient"):
                userProfile = UserProfile.objects.filter(user=user)[0]
                pkofuser = userProfile.id
                return view_patient(request,pkofuser)
        if 'home' in request.GET:
            return HttpResponseRedirect("/healthnet/doctor/")

        allP = UserProfile.objects.all()
        length = int(allP.count())
    context = {"allp" : allP, "len" : length}
    return render(request, 'doctor/doctor_view_all_patients.html', context)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def view_patient(request,pk):
    """
    Doctor view for a specific patient in the system
    :param request: Accepts a request object.
    :param pk: Private Key for a user
    :return: The view in html format for a specific patient
    """
    userProfile = UserProfile.objects.get(id=pk)
    
    prescriptions = Prescription.objects.filter(user=userProfile.user)
    plen = int(prescriptions.count())

    tests = Test.objects.filter(user=userProfile.user)
    tlen = int(tests.count())

    if request.method == 'GET':
        if 'makepscript' in request.GET:
            return HttpResponseRedirect('/healthnet/doctor/makeprescription/%s/' % userProfile.id)
        elif 'maketest' in request.GET:
            return HttpResponseRedirect('/healthnet/doctor/maketest/%s/' % userProfile.id)
        elif 'update' in request.GET:
            userProfileForm = PatientProfileForm(data=request.GET,instance=userProfile)
            if userProfileForm.is_valid():
                userProfileForm.save()
            userProfile = UserProfile.objects.get(id=pk)
        elif 'allpatients' in request.GET:
            return all_patients(request)
        elif 'admitreleaseform' in request.GET:
            return admit_release_patient(request, userProfile.id)
        elif 'transferpatient' in request.GET:
            return transfer_patient(request, userProfile.id)
        elif 'uploadfile' in request.GET:
            return upload_file(request, userProfile.id)

    userForm = PatientForm(data=model_to_dict(userProfile.user))
    userProfileForm = PatientProfileForm(data=model_to_dict(userProfile))

    userProfileForm.fields['hospital'].widget = forms.HiddenInput()

    dp = DoctorProfile.objects.get(user=request.user)
    dph = dp.hospital.filter(name=userProfile.hospital.name)
    if dph.exists() and dp.hospital.count() < 2: 
        temp = False
    else:
        temp = True

    context = {"userprofile" : userProfile, "userprofileform" : userProfileForm,
    "pscripts" : prescriptions, "tests" : tests, "plen" : plen, "tlen" : tlen,
    "cantransfer" : temp,
    "files" : PatientFile.objects.filter(user=userProfile.user),}
    return render(request, 'doctor/doctor_view_patient.html', context)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def appointments(request):
    """
    Doctor view of all of the appointments for the specific doctor
    :param request: Accepts a request object.
    :return: The view in html format for the appointments for the doctor
    """
    doc = DoctorProfile.objects.filter(user=request.user)[0]
    allAppointments = Appointment.objects.filter(doctor=doc)
    length = int(allAppointments.count())

    if request.method == 'POST':
        if 'home' in request.POST:
            return HttpResponseRedirect("/healthnet/doctor/")
        elif 'delete_all' in request.POST:
            allAppointments = allAppointments.delete()
            length = 0
        elif 'make' in request.POST:
            return HttpResponseRedirect("/healthnet/doctor/makeappointment/")

    context = {"all_appointments" : allAppointments, "len" : length}
    return render(request, 'doctor/doctor_appointment.html', context)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def make_appointment(request):
    """
    Doctor view for making a specific appointment for a specific patient
    :param request: Accepts a request object.
    :return: The view in html format for making an appointment for a user
    """
    if request.method == 'POST':
        doc_make_form = DoctorMakeAppoitmentForm(data=request.POST)

        #sets the doctor to the current Doctor
        request_copy = request.POST.copy()
        request_copy.update(doctor=DoctorProfile.objects.get(user=request.user).id)
        appointment_form = PatientAppointmentForm(data=request_copy)

        if doc_make_form.is_valid() and appointment_form.is_valid():
            appointment = appointment_form.save(commit=False)
            appointment.user = User.objects.get(username=doc_make_form.cleaned_data['username'])
            appointment.doctor = DoctorProfile.objects.get(user=request.user)
            appointment.save()

            logger.info("Doctor \"" + request.user.username + "\" has added an apointment "
                "for Patient \"" + appointment.user.username + "\" at " + str(appointment.date_time))
            return HttpResponseRedirect("/healthnet/doctor/appointments/")
        else:
            print(appointment_form.errors)
    else:
        doc_make_form = DoctorMakeAppoitmentForm()
        appointment_form = PatientAppointmentForm()
    
    appointment_form.fields['doctor'].widget = forms.HiddenInput()

    appointmentdic = []
    appointments = Appointment.objects.all()
    for appointment in appointments:
        d = appointment.date_time
        starttime = d.strftime("%Y-%m-%dT%H:%M:%S")
        appointmentdic.append({'title': appointment.user.first_name,
                               'start': starttime
                               })

    context = {"allAppointments": SafeString(simplejson.dumps(appointmentdic)),
    "doc_make_form" : doc_make_form, "appointment_form" : appointment_form,}
    return render(request, 'doctor/doctor_make_appointment.html', context)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def make_prescription(request,pk):
    """
    Doctor view for making a specific appointment for a specific patient
    :param request: Accepts a request object.
    :param pk: Private Key for a user
    :return: The view in html format for making an appointment for a user
    """
    if request.method == 'POST':
        pscript_form = PrescriptionForm(data=request.POST)

        if pscript_form.is_valid():
            script = pscript_form.save(commit=False)
            script.user = UserProfile.objects.get(id=pk).user
            u = User.objects.get(id=request.user.id)
            script.prescribed_by_doctor = DoctorProfile.objects.get(user=u)
            script.save()

            logger.info("Doctor \"" + request.user.username + "\" has added a prescription "
                "for Patient " + script.user.username + "." )
            return view_patient(request,pk)
        else:
            print(pscript_form.errors)
    else:
        pscript_form = PrescriptionForm()

    context = {"form" : pscript_form, "pk" : pk}
    return render(request, 'doctor/doctor_make_prescription.html', context)

@login_required
@user_passes_test(is_doctor, login_url='/healthnet/restricted/')
def make_test(request,pk):
    """
    Doctor view for making a specific appointment for making a test
    :param request: Accepts a request object.
    :param pk: Private Key for a user
    :return: The view in html format for making an appointment for a user
    """
    if request.method == 'POST':
        test_form = TestForm(data=request.POST)

        if test_form.is_valid():
            test = test_form.save(commit=False)
            test.user = UserProfile.objects.get(id=pk).user
            u = User.objects.get(id=request.user.id)
            test.prescribed_by_doctor = DoctorProfile.objects.get(user=u)
            test.save()

            logger.info("Doctor \"" + request.user.username + "\" has added a test "
                "for Patient \"" + test.user.username + "\"." )

HealthNetR2/oursite/doctor/templates/doctor/doctor_all_patients.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load doctor_tags %}
        <div id="doctor_allpatients_body">
        {% if user|is_doctor %}
            <h1>All Patients for Doctor: {{ user.username }}</h1>
            <form id="allpatients" method="post" action="{% url 'doctor:index' %}">{% csrf_token %}
                {% for e in allp %}
                    <p>Patient User: {{ e.user.username }}<br>
                    First Name: {{ e.user.first_name }}<br>
                    Last Name: {{ e.user.last_name}}
                    {% if len > 0 %}
                        <input type="hidden" name="yes" value=""><br >
                        <a href="{% url 'doctor:viewpatient' e.id %}"><input type="button" value="View Patient"/></a>
                    {% endif %}
                    <br>
                {% endfor %}
                <div id="button_box">
                    <input type="submit" name='home' value="Go Back To Home" />
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}
            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_appointment.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load doctor_tags %}
        <div id="doctor_appt_body">
        {% if user|is_doctor %}
            <h1>Appointments</h1>
            <h2>Doctor: {{ user.first_name }}</h2>
            <form id="alluserappointments" method="post" action="{% url 'doctor:allappointments' %}">{% csrf_token %}
                {% for e in all_appointments %}
                    <p>Patient: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>{{ e.date_time }}
                    <br>Location: {{ e.user|get_location }}
                    {% if len > 0 %}
                        <input type="hidden" name="yes" value=""><br >
                        <a href="{% url 'doctor:editapp' e.id %}"><input type="button" value="Edit"/></a>
                        <a href="{% url 'doctor:deleteapp' e.id %}"><input type="button" value="Delete"/></a>
                    {% endif %}
                    <br>
                {% endfor %}
                <div id="button_box">
                    <input type="submit" name='make' value="Make Appointment" />
                    <input type="submit" name='delete_all' value="Delete All Appointments" onclick="return confirm('Are you sure?')" />
                    <input type="submit" name='home' value="Go Back To Home" />
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_edit_test.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Edit Appointment</title>
    </head>
            {% block body_block %}

    {% load doctor_tags %}
    {% if user|is_doctor %}
    <body>
    <div id="doctor_edittest">
        <form method="post" action="{% url 'doctor:edittest' pk pk2 %}">
            {% csrf_token %}
            <h1>Edit Test</h1>
            {{ test_form.as_p }}
            <input type="submit" name="Save" value="Save"/>
            <a href="{% url 'doctor:viewpatient' pk2 %}"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}
    {% endblock %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_make_prescription.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Make Prescription</title>
    </head>
    
    {% load doctor_tags %}
    {% if user|is_doctor %}
    <body>
    {% block body_block %}
    <div id="doctor_makescript">
        <form id="make_prescription" method="post" action="{% url 'doctor:makepscript' pk %}">
            {% csrf_token %}
            <h1>Make Prescription</h1>
            {{ form.as_p }}
            <input type="submit" name="Submit" value="Submit" />
            <a href="{% url 'doctor:viewpatient' pk %}"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% endblock %}
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_make_test.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Make Test</title>
    </head>
    
    {% load doctor_tags %}
    {% if user|is_doctor %}
    <body>
    {% block body_block %}
    <div id="doctor_maketest">
        <form id="make_test" method="post" action="{% url 'doctor:maketest' pk %}">
            {% csrf_token %}
            <h1>Make Test</h1>
            {{ form.as_p }}
            <input type="submit" name="Submit" value="Submit" />
            <a href="{% url 'doctor:viewpatient' pk %}"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% endblock %}
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_transfer_patient.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Transfer</title>
    </head>
    
    {% load doctor_tags %}
    {% if user|is_doctor %}
    <body>
    {% block body_block %}
    <div id="doctor_transfer">
        <form id="make_prescription" method="post" action="{% url 'doctor:transferpatient' pk %}">
            {% csrf_token %}
            <h1>Transfer Patient</h1>
            <p>Patient: {{ patient.user.username }}</p>
            {{ form.as_p }}
            <input type="submit" name="Submit" value="Submit" />
            <a href="{% url 'doctor:viewpatient' pk %}"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% endblock %}
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_upload_file.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>Upload File</title>
    </head>
    
    {% load doctor_tags %}
    {% if user|is_doctor %}
    <body>
    {% block body_block %}
    <div id="doctor_upload">
        <form id="make_prescription" method="post" action="{% url 'doctor:uploadfile' patient.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>File Upload</h1>
            <p>Patient: {{ patient.user.username }}</p>
            {{ form }}
            <br>
            <input type="submit" name="Submit" value="Submit" />
            <a href="{% url 'doctor:viewpatient' patient.id %}"><input type="button" value="Cancel"/></a>
        </form>
        </div>
    </body>
    {% endblock %}
    {% else %}
       {% include "healthnet/index.html" %}
    {% endif %}

        {% block cal_block %}
        {% endblock %}
</html>

HealthNetR2/oursite/doctor/templates/doctor/doctor_view_patient.html
{% extends 'doctorbase.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <body>
        {% block body_block %}
        {% csrf_token %}
        {% load doctor_tags %}
        <div id="doctor_viewpatient_body">
        {% if user|is_doctor %}
            <h1>Patient for Doctor: {{ user.first_name }}</h1>
            <form id="viewpatient" method="get" action="{% url 'doctor:viewpatient' userprofile.id %}">{% csrf_token %}
                <b>Username: </b> {{ userprofile.user.username }}<br><br>
                <b>First Name: </b> {{ userprofile.user.first_name }}<br><br>
                <b>Last Name: </b> {{ userprofile.user.last_name }}<br><br>
                <b>Hospital: </b> {{ userprofile.hospital.name }}<br><br>
                <b>Currently Admitted: </b> {{ userprofile.is_in_hospital }}<br>
                {{ userprofileform.as_p }}
                <input type="submit" name='update' value="Update" />
                <br>
                <h2>Prescriptions</h2>
                {% if plen == 0 %}
                    <p> None </p>
                {% endif %}
                {% for e in pscripts %}
                    {% if plen > 0 %}
                    <p>Name of Patient: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>Doctor who Prescribed: {{ e.prescribed_by_doctor }}
                    <br>Name of Prescription: {{ e.name }}
                    <br>Amount to Take: {{ e.amount }}
                    <br>Reason: {{ e.reason }}
                    <br>
                        <a href="{% url 'doctor:deletepscript' e.id userprofile.id%}"><input type="button" value="Delete"/></a>
                    <br>
                    {% endif %}
                {% endfor %}

                <h2>Tests</h2>
                {% if tlen == 0 %}
                    <p> None </p>
                {% endif %}
                {% for e in tests %}
                    {% if tlen > 0 %}
                    <p>Name of Patient: {{ e.user.first_name }} {{ e.user.last_name}}
                    <br>Doctor who Prescribed: {{ e.prescribed_by_doctor }}
                    <br>Name of Test: {{ e.name_of_test }}
                    <br>Result: {{ e.result }}
                    <br>Reason/Comments: {{ e.reason }}
                    <br>
                        <a href="{% url 'doctor:edittest' e.id userprofile.id %}"><input type="button" value="Edit"/></a>
                        <a href="{% url 'doctor:deletetest' e.id userprofile.id %}"><input type="button" value="Delete"/></a>
                    <br>
                    {% endif %}
                {% endfor %}

                <h2>Files (Click FileName to View/Download)</h2>
                {% if files %}
                    {% for e in files %}
                        <a href="{{ e.patient_file.url }}">{{ e.file_name }}{{ e|extension }}</a>
                        <a href="{% url 'doctor:deletefile' e.id userprofile.id %}"><input type="button" value="Delete"/></a><br>
                    {% endfor %}
                {% else %}
                    <p>None</p>
                {% endif %}

                <div id="button_box">
                    <input type="submit" name='makepscript' value="Make Prescription" />
                    <input type="submit" name='maketest' value="Make Test" />
                    <input type="submit" name='allpatients' value="View All Patients" />
                    <input type="submit" name='admitreleaseform' value="Admit/Release Patient" />
                    <input type="submit" name='uploadfile' value="Upload File" />
                    {% if cantransfer %}
                        <input type="submit" name='transferpatient' value="Transfer Patient" />
                    {% endif %}
                </div>
            </form>
            {% else %}
                {% include "healthnet/index.html" %}
            {% endif %}
            </div>
            {% endblock %}

            {% block cal_block %}
        {% endblock %}
    </body>
</html>